### ISSUE TITLE
Playground broken

### ISSUE THREAD

**Issue by L1ghtman2k** [go-gorm/playground#57]
I am trying to submit an issue, but for some reason it doesn't run the code:

https://github.com/go-gorm/playground/pull/56

**Comment by jinzhu** [comment]
https://github.com/go-gorm/playground/pull/56/files#diff-53618cae32e23ae47e1c35f10da92654L7-L9

Those comments are useful and should not be delete

**Comment by L1ghtman2k** [comment]
Got it, thank you!
